
# Build Docker image
- name: Build an image and push it to local repo
  docker_image:
    build:
      path: '~/COMP90024_Project/frontend'
      pull: yes
    name: frontend
    tag: latest
    source: build
    force_source: yes
  become: yes
  environment: "{{ proxy_env }}"

# Stop Docker container
- name: Stop Docker container
  become: yes
  docker_container:
    name: frontend
    state: absent

# Create new Docker container and start container
- name: Create and start Docker container
  become: yes
  docker_container:
    name: frontend
    image: frontend
    state: started
    pull: false
    recreate: true
    published_ports:
      - '80:80'