

- name: Generate nginx.conf
  template:
    src: nginx.conf.j2
    dest: /home/ubuntu/nginx.conf
  become: yes

# Create new Docker container and start container
- name: Create and start Docker container
  become: yes
  docker_container:
    name: frontend
    image: frontend
    state: started
    pull: false
    recreate: true
    published_ports:
      - '80:80'
    volumes:
      - "/home/ubuntu/nginx.conf:/etc/nginx/conf.d/default.conf"