
# Build Docker image
- name: Build an image and push it to local repo
  docker_image:
    build:
      path: '~/COMP90024_Project/backend/mastodon'
      pull: yes
    name: mastodon
    tag: latest
    source: build
    force_source: yes
  become: yes
  environment: "{{ proxy_env }}"

# Create new Docker container and start container
- name: Create and start Docker container
  become: yes
  docker_container:
    name: '{{ item.name }}'
    image: mastodon
    state: started
    pull: false
    recreate: true
    env:
      API_URL: "{{ item.API_URL }}"
      ACCESS_TOKEN: "{{ item.ACCESS_TOKEN }}"
      NLP_HOST: "{{ groups['ServerNodes'][0] }}"
      NLP_PORT: "{{ ports.nlp }}"
      WRITE_DB_HOST: "{{ groups['MasterNode'][0] }}"
      WRITE_DB_PORT: "{{ ports.couchdb }}"
  loop: "{{ mastodons }}"