# Build Docker image
- name: Build an image of backend and push it to local repo
  docker_image:
    build:
      path: '~/COMP90024_Project'
      dockerfile: Titter.Dockerfile
      pull: yes
    name: "{{ groups['ServerNodes'][0] }}:{{ ports.registry }}/comp90024/process"
    tag: latest
    source: build
    push: yes
    force_source: yes
  become: yes
  environment: "{{ proxy_env }}"